/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author roche
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        buttonLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAddUsers = new javax.swing.JMenu();
        menuAddDoctor = new javax.swing.JMenuItem();
        menuAddCommunityAdmin = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuDoctor = new javax.swing.JMenuItem();
        menuCommunity = new javax.swing.JMenuItem();
        menuCreate = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));

        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/female-doctor-nurse-stethoscope-hands-ecg-line-medical-green-background-health-care-banner-web-sites-copy-173537104.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        menuAddUsers.setText("Add Users");
        menuAddUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuAddDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuAddDoctor.setText("Doctor");
        menuAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddDoctorActionPerformed(evt);
            }
        });
        menuAddUsers.add(menuAddDoctor);

        menuAddCommunityAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuAddCommunityAdmin.setText("Community Admin");
        menuAddCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCommunityAdminActionPerformed(evt);
            }
        });
        menuAddUsers.add(menuAddCommunityAdmin);

        jMenuBar1.add(menuAddUsers);

        menuEdit.setText("Edit Details");
        menuEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuDoctor.setText("Doctor Details");
        menuEdit.add(menuDoctor);

        menuCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCommunity.setText("Community Admin");
        menuCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCommunityActionPerformed(evt);
            }
        });
        menuEdit.add(menuCommunity);

        jMenuBar1.add(menuEdit);

        menuCreate.setText("Create");
        menuCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("Add Hospitals");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCreate.add(jMenuItem1);

        jMenuBar1.add(menuCreate);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1310, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogOut))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonLogOut)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                        .addGap(25, 25, 25))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddDoctorActionPerformed
        // TODO add your handling code here:
        DoctorDirectory doctor = new DoctorDirectory();
        doctor.setVisible(true);
       
    }//GEN-LAST:event_menuAddDoctorActionPerformed

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        // TODO add your handling code here:
        HospitalLoginPage page = new HospitalLoginPage();
        this.setVisible(false);
        page.setVisible(true);
    }//GEN-LAST:event_buttonLogOutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        CreateHospital hospital = new CreateHospital();
        hospital.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuAddCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCommunityAdminActionPerformed
        // TODO add your handling code here:
        Community community = new Community();
        community.setVisible(true);
    }//GEN-LAST:event_menuAddCommunityAdminActionPerformed

    private void menuCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCommunityActionPerformed
        // TODO add your handling code here:
        Community community = new Community();
        community.setVisible(true);
    }//GEN-LAST:event_menuCommunityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem menuAddCommunityAdmin;
    private javax.swing.JMenuItem menuAddDoctor;
    private javax.swing.JMenu menuAddUsers;
    private javax.swing.JMenuItem menuCommunity;
    private javax.swing.JMenu menuCreate;
    private javax.swing.JMenuItem menuDoctor;
    private javax.swing.JMenu menuEdit;
    // End of variables declaration//GEN-END:variables
}
