/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;


import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author roche
 */
public class HospitalLoginPage extends javax.swing.JFrame {
 Connection con=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    /**
     * Creates new form HospitalLoginPage
     */
    public HospitalLoginPage() {
        initComponents();
        //con = Connect.ConnectDB();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboUsers = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        buttonRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboUsers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select user", "System Admin", "Doctor", "Patient", "Community Admin" }));
        comboUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUsersActionPerformed(evt);
            }
        });
        getContentPane().add(comboUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogin.setText("Login As:");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setText("Username:");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 20));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 220, 40));

        buttonLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 220, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Don't have an account?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        buttonRegister.setText("Register");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String usertype = comboUsers.getSelectedItem().toString();

        if (comboUsers.getSelectedItem().equals("Select user")) {
            JOptionPane.showMessageDialog( this, "Please select user type");
            return;

        }
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog( this, "Please enter user name");
            return;
        }
        if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog( this, "Please enter password");
            return;

        }

        con = Connect.ConnectDB();
        if (comboUsers.getSelectedItem().equals("Patient")){
        String sq1= "select * from patient_registration where username= ? and password =?";
        try{
            pst=con.prepareStatement(sq1);
            pst.setString(1, username);
            pst.setString(2, password);
            //pst.setString(3, usertype);
            rs= pst.executeQuery();
            if (rs.next()){
                this.setVisible(false);
                Encounter encounter =new Encounter();
                encounter.setVisible(true);
                String user = txtUsername.getText();
                
                
                encounter.username(user);
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Login Failed..Try again !");
            }
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
            // TODO add your handling code here:
        }
        }
        if (comboUsers.getSelectedItem().equals("System Admin")){
        String sql2= ("select * from login where username = ? and password = ? and usertype = ?");
        try{
            pst=con.prepareStatement(sql2);
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, usertype);
            rs= pst.executeQuery();
            if (rs.next()){
                this.setVisible(false);
                Admin admin =new Admin();
                admin.setVisible(true);
                
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Login Failed..Try again !");
            }
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
            // TODO add your handling code here:
        }
        }
        
        if (comboUsers.getSelectedItem().equals("Doctor")){
        String sql3= "select * from doctor_details where username = ? and password = ?";
        try{
            pst=con.prepareStatement(sql3);
            pst.setString(1, username);
            pst.setString(2, password);
           // pst.setString(3, usertype);
            rs= pst.executeQuery();
            if (rs.next()){
                this.setVisible(false);
                Doctor doctor = new Doctor();
                doctor.setVisible(true);
                String user = txtUsername.getText();
                doctor.username(user);
                //doctor.ViewAppointment(id);
                
                
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Login Failed..Try again !");
            }
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
            // TODO add your handling code here:
        }
        }
        if (comboUsers.getSelectedItem().equals("Community Admin")){
        String sql4= "select * from communityadmin where username = ? and password = ?";
        try{
            pst=con.prepareStatement(sql4);
            pst.setString(1, username);
            pst.setString(2, password);
           // pst.setString(3, usertype);
            rs= pst.executeQuery();
            if (rs.next()){
                this.setVisible(false);
                PatientDirectory patient = new PatientDirectory();
                patient.setVisible(true);
                String user = comboUsers.getSelectedItem().toString();
                patient.username(user);
                
                
                
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Login Failed..Try again !");
            }
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
            // TODO add your handling code here:
        }
        }
        
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void comboUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsersActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboUsersActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:
        PatientDirectory register = new PatientDirectory();
        register.setVisible(true);
        
    }//GEN-LAST:event_buttonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JComboBox<String> comboUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
